name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install -y poppler-utils
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build package
      run: make
    - name: Check code
      run: make check
    - name: Test
      run: make test

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag papercheck
      - name: Run setup
        run: docker run papercheck bash -c "make test"